// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Access struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type Booking struct {
	ID         int        `json:"id"`
	CustomerID int        `json:"customerId"`
	FlightID   int        `json:"flightId"`
	Code       string     `json:"code"`
	Status     string     `json:"status"`
	TicketID   int        `json:"ticketId"`
	CreatedAt  *time.Time `json:"createdAt,omitempty"`
	UpdatedAt  *time.Time `json:"updatedAt,omitempty"`
}

type BookingFullResponse struct {
	ID        int        `json:"id"`
	Customer  *Customer  `json:"customer"`
	Flight    *Flight    `json:"flight"`
	Code      string     `json:"code"`
	Status    string     `json:"status"`
	TicketID  int        `json:"ticketId"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type BookingOps struct {
	CreateBooking *CustomBookingResponse `json:"createBooking,omitempty"`
	CancelBooking *CustomCancelResponse  `json:"cancelBooking,omitempty"`
}

type BookingQuery struct {
	ViewBooking    *CustomViewBookingResponse    `json:"viewBooking,omitempty"`
	BookingHistory *CustomBookingHistoryResponse `json:"bookingHistory,omitempty"`
	Bookings       *BookingResponse              `json:"bookings,omitempty"`
}

type BookingResponse struct {
	Data  []*BookingFullResponse `json:"data"`
	Page  *int                   `json:"page,omitempty"`
	Limit *int                   `json:"limit,omitempty"`
	Total *int                   `json:"total,omitempty"`
}

type CancelBookingInput struct {
	BookingCode string `json:"bookingCode"`
}

type CancelResponse struct {
	BookingCode *string    `json:"bookingCode,omitempty"`
	CancelDate  *time.Time `json:"cancelDate,omitempty"`
	CustomerID  *int       `json:"customerId,omitempty"`
	FlightID    *int       `json:"flightId,omitempty"`
	Status      *string    `json:"status,omitempty"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CreateBookingInput struct {
	FlightName     string  `json:"flightName"`
	Email          *string `json:"email,omitempty"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	Name           *string `json:"name,omitempty"`
	Address        *string `json:"address,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	IdentifyNumber *string `json:"identifyNumber,omitempty"`
	MemberCode     *string `json:"memberCode,omitempty"`
	TicketType     int     `json:"ticketType"`
}

type CreateFlightInput struct {
	Name                 string     `json:"name"`
	From                 string     `json:"from"`
	To                   string     `json:"to"`
	DepartureDate        string     `json:"departureDate"`
	ArrivalDate          string     `json:"arrivalDate"`
	AvailableFirstSlot   int        `json:"available_first_slot"`
	AvailableEconomySlot int        `json:"available_economy_slot"`
	Status               string     `json:"status"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	AccessID int    `json:"accessID"`
}

type CustomBookingHistoryResponse struct {
	Code  int                    `json:"code"`
	Data  []*ViewBookingResponse `json:"data,omitempty"`
	Page  *int                   `json:"page,omitempty"`
	Limit *int                   `json:"limit,omitempty"`
	Total *int                   `json:"total,omitempty"`
}

type CustomBookingResponse struct {
	Code int                          `json:"code"`
	Data *CustomCreateBookingResponse `json:"data"`
}

type CustomCancelResponse struct {
	Code int             `json:"code"`
	Data *CancelResponse `json:"data,omitempty"`
}

type CustomCreateBookingResponse struct {
	BookingCode *string    `json:"bookingCode,omitempty"`
	BookingDate *time.Time `json:"bookingDate,omitempty"`
	CustomerID  *int       `json:"customerId,omitempty"`
	FlightID    *int       `json:"flightId,omitempty"`
	Status      *string    `json:"status,omitempty"`
}

type CustomCustomerResponse struct {
	Data  []*Customer `json:"data,omitempty"`
	Page  *int        `json:"page,omitempty"`
	Limit *int        `json:"limit,omitempty"`
	Total *int        `json:"total,omitempty"`
}

type CustomFlightResponse struct {
	Data  []*Flight `json:"data,omitempty"`
	Page  *int      `json:"page,omitempty"`
	Limit *int      `json:"limit,omitempty"`
	Total *int      `json:"total,omitempty"`
}

type CustomLoginResponse struct {
	UserID *int    `json:"userId,omitempty"`
	Token  *string `json:"token,omitempty"`
}

type CustomRegisterResponse struct {
	Data  *User   `json:"data,omitempty"`
	Token *string `json:"token,omitempty"`
}

type CustomUserResponse struct {
	Data  []*UserResponse `json:"data,omitempty"`
	Page  *int            `json:"page,omitempty"`
	Limit *int            `json:"limit,omitempty"`
	Total *int            `json:"total,omitempty"`
}

type CustomViewBookingResponse struct {
	Code int                  `json:"code"`
	Data *ViewBookingResponse `json:"data"`
}

type Customer struct {
	ID             int        `json:"id"`
	Name           string     `json:"name"`
	Email          string     `json:"email"`
	Address        string     `json:"address"`
	PhoneNumber    string     `json:"phoneNumber"`
	IdentifyNumber string     `json:"identifyNumber"`
	DateOfBirth    string     `json:"dateOfBirth"`
	MemberCode     string     `json:"memberCode"`
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}

type CustomerOps struct {
	ChangePassword *string `json:"changePassword,omitempty"`
	UpdateCustomer *string `json:"updateCustomer,omitempty"`
}

type CustomerQuery struct {
	Customers *CustomCustomerResponse `json:"customers"`
}

type DeleteFlightInput struct {
	ID int `json:"id"`
}

type DeleteUserInput struct {
	ID int `json:"id"`
}

type Flight struct {
	ID                   int        `json:"id"`
	Name                 string     `json:"name"`
	From                 string     `json:"from"`
	To                   string     `json:"to"`
	DepartureDate        time.Time  `json:"departureDate"`
	ArrivalDate          time.Time  `json:"arrivalDate"`
	AvailableFirstSlot   int        `json:"available_first_slot"`
	AvailableEconomySlot int        `json:"available_economy_slot"`
	Status               string     `json:"status"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`
}

type FlightOps struct {
	CreateFlight *string `json:"createFlight,omitempty"`
	UpdateFlight *string `json:"updateFlight,omitempty"`
}

type FlightQuery struct {
	SearchFlights *SearchFlightResponse `json:"searchFlights,omitempty"`
	Flights       *CustomFlightResponse `json:"flights"`
}

type GetFlightInput struct {
	From          string `json:"from"`
	To            string `json:"to"`
	DepartureDate string `json:"departureDate"`
	ArrivalDate   string `json:"arrivalDate"`
}

type GetFlightResponse struct {
	Data []*Flight `json:"data,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterCustomer struct {
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	CustomerName   string  `json:"customerName"`
	Address        string  `json:"address"`
	PhoneNumber    string  `json:"phoneNumber"`
	IdentifyNumber string  `json:"identifyNumber"`
	DateOfBirth    string  `json:"dateOfBirth"`
	MemberCode     *string `json:"memberCode,omitempty"`
}

type RegisterUserRes struct {
	Token *string `json:"token,omitempty"`
	ID    *int    `json:"id,omitempty"`
}

type SearchFlightInput struct {
	From          string `json:"from"`
	To            string `json:"to"`
	DepartureDate string `json:"departureDate"`
	ArrivalDate   string `json:"arrivalDate"`
}

type SearchFlightResponse struct {
	Data  []*Flight `json:"data,omitempty"`
	Page  *int      `json:"page,omitempty"`
	Limit *int      `json:"limit,omitempty"`
	Total *int      `json:"total,omitempty"`
}

type UpdateAccessIDInput struct {
	AccessID int `json:"accessID"`
}

type UpdateCustomerInput struct {
	Name           *string `json:"name,omitempty"`
	Email          *string `json:"email,omitempty"`
	Address        *string `json:"address,omitempty"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	IdentifyNumber *string `json:"identifyNumber,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	MemberCode     *string `json:"memberCode,omitempty"`
}

type UpdateFlightInput struct {
	Name                 *string    `json:"name,omitempty"`
	DepartureDate        *string    `json:"departureDate,omitempty"`
	ArrivalDate          *string    `json:"arrivalDate,omitempty"`
	AvailableFirstSlot   *int       `json:"available_first_slot,omitempty"`
	AvailableEconomySlot *int       `json:"available_economy_slot,omitempty"`
	Status               *string    `json:"status,omitempty"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`
}

type UpdateUserPasswordInput struct {
	OldPassword string `json:"oldPassword"`
	Password    string `json:"password"`
}

type User struct {
	ID         int        `json:"id"`
	Email      string     `json:"email"`
	Password   string     `json:"password"`
	CustomerID int        `json:"customerID"`
	AccessID   int        `json:"accessID"`
	CreatedAt  *time.Time `json:"createdAt,omitempty"`
	UpdatedAt  *time.Time `json:"updatedAt,omitempty"`
}

type UserOps struct {
	CreateUser         *string                 `json:"createUser,omitempty"`
	UpdateUserAccessID *string                 `json:"updateUserAccessId,omitempty"`
	UpdateUserPassword *string                 `json:"updateUserPassword,omitempty"`
	RegisterCustomer   *CustomRegisterResponse `json:"registerCustomer,omitempty"`
	Login              *CustomLoginResponse    `json:"login,omitempty"`
}

type UserQuery struct {
	Users *CustomUserResponse `json:"users"`
}

type UserResponse struct {
	ID         int        `json:"id"`
	Email      string     `json:"email"`
	Password   string     `json:"password"`
	Customer   *Customer  `json:"customer"`
	AccessType *Access    `json:"accessType"`
	CreatedAt  *time.Time `json:"createdAt,omitempty"`
	UpdatedAt  *time.Time `json:"updatedAt,omitempty"`
}

type ViewBookingResponse struct {
	BookingCode   *string    `json:"bookingCode,omitempty"`
	BookingDate   *time.Time `json:"bookingDate,omitempty"`
	BookingStatus *string    `json:"bookingStatus,omitempty"`
	Customer      *Customer  `json:"customer,omitempty"`
	Flight        *Flight    `json:"flight,omitempty"`
}
