// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mock-project/grpc/flight-grpc/ent/flight"
	"mock-project/grpc/flight-grpc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FlightUpdate is the builder for updating Flight entities.
type FlightUpdate struct {
	config
	hooks    []Hook
	mutation *FlightMutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (fu *FlightUpdate) Where(ps ...predicate.Flight) *FlightUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetName sets the "name" field.
func (fu *FlightUpdate) SetName(s string) *FlightUpdate {
	fu.mutation.SetName(s)
	return fu
}

// SetFrom sets the "from" field.
func (fu *FlightUpdate) SetFrom(s string) *FlightUpdate {
	fu.mutation.SetFrom(s)
	return fu
}

// SetTo sets the "to" field.
func (fu *FlightUpdate) SetTo(s string) *FlightUpdate {
	fu.mutation.SetTo(s)
	return fu
}

// SetDepartureDate sets the "departure_date" field.
func (fu *FlightUpdate) SetDepartureDate(t time.Time) *FlightUpdate {
	fu.mutation.SetDepartureDate(t)
	return fu
}

// SetArrivalDate sets the "arrival_date" field.
func (fu *FlightUpdate) SetArrivalDate(t time.Time) *FlightUpdate {
	fu.mutation.SetArrivalDate(t)
	return fu
}

// SetAvailableFirstSlot sets the "available_first_slot" field.
func (fu *FlightUpdate) SetAvailableFirstSlot(i int) *FlightUpdate {
	fu.mutation.ResetAvailableFirstSlot()
	fu.mutation.SetAvailableFirstSlot(i)
	return fu
}

// SetNillableAvailableFirstSlot sets the "available_first_slot" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableAvailableFirstSlot(i *int) *FlightUpdate {
	if i != nil {
		fu.SetAvailableFirstSlot(*i)
	}
	return fu
}

// AddAvailableFirstSlot adds i to the "available_first_slot" field.
func (fu *FlightUpdate) AddAvailableFirstSlot(i int) *FlightUpdate {
	fu.mutation.AddAvailableFirstSlot(i)
	return fu
}

// SetAvailableEconomySlot sets the "available_economy_slot" field.
func (fu *FlightUpdate) SetAvailableEconomySlot(i int) *FlightUpdate {
	fu.mutation.ResetAvailableEconomySlot()
	fu.mutation.SetAvailableEconomySlot(i)
	return fu
}

// SetNillableAvailableEconomySlot sets the "available_economy_slot" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableAvailableEconomySlot(i *int) *FlightUpdate {
	if i != nil {
		fu.SetAvailableEconomySlot(*i)
	}
	return fu
}

// AddAvailableEconomySlot adds i to the "available_economy_slot" field.
func (fu *FlightUpdate) AddAvailableEconomySlot(i int) *FlightUpdate {
	fu.mutation.AddAvailableEconomySlot(i)
	return fu
}

// SetStatus sets the "status" field.
func (fu *FlightUpdate) SetStatus(f flight.Status) *FlightUpdate {
	fu.mutation.SetStatus(f)
	return fu
}

// SetUpdatedAt sets the "updated_at" field.
func (fu *FlightUpdate) SetUpdatedAt(t time.Time) *FlightUpdate {
	fu.mutation.SetUpdatedAt(t)
	return fu
}

// Mutation returns the FlightMutation object of the builder.
func (fu *FlightUpdate) Mutation() *FlightMutation {
	return fu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FlightUpdate) Save(ctx context.Context) (int, error) {
	fu.defaults()
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FlightUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FlightUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FlightUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fu *FlightUpdate) defaults() {
	if _, ok := fu.mutation.UpdatedAt(); !ok {
		v := flight.UpdateDefaultUpdatedAt()
		fu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FlightUpdate) check() error {
	if v, ok := fu.mutation.AvailableFirstSlot(); ok {
		if err := flight.AvailableFirstSlotValidator(v); err != nil {
			return &ValidationError{Name: "available_first_slot", err: fmt.Errorf(`ent: validator failed for field "Flight.available_first_slot": %w`, err)}
		}
	}
	if v, ok := fu.mutation.AvailableEconomySlot(); ok {
		if err := flight.AvailableEconomySlotValidator(v); err != nil {
			return &ValidationError{Name: "available_economy_slot", err: fmt.Errorf(`ent: validator failed for field "Flight.available_economy_slot": %w`, err)}
		}
	}
	if v, ok := fu.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	return nil
}

func (fu *FlightUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt64))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
	}
	if value, ok := fu.mutation.From(); ok {
		_spec.SetField(flight.FieldFrom, field.TypeString, value)
	}
	if value, ok := fu.mutation.To(); ok {
		_spec.SetField(flight.FieldTo, field.TypeString, value)
	}
	if value, ok := fu.mutation.DepartureDate(); ok {
		_spec.SetField(flight.FieldDepartureDate, field.TypeTime, value)
	}
	if value, ok := fu.mutation.ArrivalDate(); ok {
		_spec.SetField(flight.FieldArrivalDate, field.TypeTime, value)
	}
	if value, ok := fu.mutation.AvailableFirstSlot(); ok {
		_spec.SetField(flight.FieldAvailableFirstSlot, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AddedAvailableFirstSlot(); ok {
		_spec.AddField(flight.FieldAvailableFirstSlot, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AvailableEconomySlot(); ok {
		_spec.SetField(flight.FieldAvailableEconomySlot, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AddedAvailableEconomySlot(); ok {
		_spec.AddField(flight.FieldAvailableEconomySlot, field.TypeInt, value)
	}
	if value, ok := fu.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := fu.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FlightUpdateOne is the builder for updating a single Flight entity.
type FlightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightMutation
}

// SetName sets the "name" field.
func (fuo *FlightUpdateOne) SetName(s string) *FlightUpdateOne {
	fuo.mutation.SetName(s)
	return fuo
}

// SetFrom sets the "from" field.
func (fuo *FlightUpdateOne) SetFrom(s string) *FlightUpdateOne {
	fuo.mutation.SetFrom(s)
	return fuo
}

// SetTo sets the "to" field.
func (fuo *FlightUpdateOne) SetTo(s string) *FlightUpdateOne {
	fuo.mutation.SetTo(s)
	return fuo
}

// SetDepartureDate sets the "departure_date" field.
func (fuo *FlightUpdateOne) SetDepartureDate(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetDepartureDate(t)
	return fuo
}

// SetArrivalDate sets the "arrival_date" field.
func (fuo *FlightUpdateOne) SetArrivalDate(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetArrivalDate(t)
	return fuo
}

// SetAvailableFirstSlot sets the "available_first_slot" field.
func (fuo *FlightUpdateOne) SetAvailableFirstSlot(i int) *FlightUpdateOne {
	fuo.mutation.ResetAvailableFirstSlot()
	fuo.mutation.SetAvailableFirstSlot(i)
	return fuo
}

// SetNillableAvailableFirstSlot sets the "available_first_slot" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableAvailableFirstSlot(i *int) *FlightUpdateOne {
	if i != nil {
		fuo.SetAvailableFirstSlot(*i)
	}
	return fuo
}

// AddAvailableFirstSlot adds i to the "available_first_slot" field.
func (fuo *FlightUpdateOne) AddAvailableFirstSlot(i int) *FlightUpdateOne {
	fuo.mutation.AddAvailableFirstSlot(i)
	return fuo
}

// SetAvailableEconomySlot sets the "available_economy_slot" field.
func (fuo *FlightUpdateOne) SetAvailableEconomySlot(i int) *FlightUpdateOne {
	fuo.mutation.ResetAvailableEconomySlot()
	fuo.mutation.SetAvailableEconomySlot(i)
	return fuo
}

// SetNillableAvailableEconomySlot sets the "available_economy_slot" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableAvailableEconomySlot(i *int) *FlightUpdateOne {
	if i != nil {
		fuo.SetAvailableEconomySlot(*i)
	}
	return fuo
}

// AddAvailableEconomySlot adds i to the "available_economy_slot" field.
func (fuo *FlightUpdateOne) AddAvailableEconomySlot(i int) *FlightUpdateOne {
	fuo.mutation.AddAvailableEconomySlot(i)
	return fuo
}

// SetStatus sets the "status" field.
func (fuo *FlightUpdateOne) SetStatus(f flight.Status) *FlightUpdateOne {
	fuo.mutation.SetStatus(f)
	return fuo
}

// SetUpdatedAt sets the "updated_at" field.
func (fuo *FlightUpdateOne) SetUpdatedAt(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetUpdatedAt(t)
	return fuo
}

// Mutation returns the FlightMutation object of the builder.
func (fuo *FlightUpdateOne) Mutation() *FlightMutation {
	return fuo.mutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (fuo *FlightUpdateOne) Where(ps ...predicate.Flight) *FlightUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FlightUpdateOne) Select(field string, fields ...string) *FlightUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Flight entity.
func (fuo *FlightUpdateOne) Save(ctx context.Context) (*Flight, error) {
	fuo.defaults()
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FlightUpdateOne) SaveX(ctx context.Context) *Flight {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FlightUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FlightUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fuo *FlightUpdateOne) defaults() {
	if _, ok := fuo.mutation.UpdatedAt(); !ok {
		v := flight.UpdateDefaultUpdatedAt()
		fuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FlightUpdateOne) check() error {
	if v, ok := fuo.mutation.AvailableFirstSlot(); ok {
		if err := flight.AvailableFirstSlotValidator(v); err != nil {
			return &ValidationError{Name: "available_first_slot", err: fmt.Errorf(`ent: validator failed for field "Flight.available_first_slot": %w`, err)}
		}
	}
	if v, ok := fuo.mutation.AvailableEconomySlot(); ok {
		if err := flight.AvailableEconomySlotValidator(v); err != nil {
			return &ValidationError{Name: "available_economy_slot", err: fmt.Errorf(`ent: validator failed for field "Flight.available_economy_slot": %w`, err)}
		}
	}
	if v, ok := fuo.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	return nil
}

func (fuo *FlightUpdateOne) sqlSave(ctx context.Context) (_node *Flight, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt64))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for _, f := range fields {
			if !flight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
	}
	if value, ok := fuo.mutation.From(); ok {
		_spec.SetField(flight.FieldFrom, field.TypeString, value)
	}
	if value, ok := fuo.mutation.To(); ok {
		_spec.SetField(flight.FieldTo, field.TypeString, value)
	}
	if value, ok := fuo.mutation.DepartureDate(); ok {
		_spec.SetField(flight.FieldDepartureDate, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.ArrivalDate(); ok {
		_spec.SetField(flight.FieldArrivalDate, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.AvailableFirstSlot(); ok {
		_spec.SetField(flight.FieldAvailableFirstSlot, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AddedAvailableFirstSlot(); ok {
		_spec.AddField(flight.FieldAvailableFirstSlot, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AvailableEconomySlot(); ok {
		_spec.SetField(flight.FieldAvailableEconomySlot, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AddedAvailableEconomySlot(); ok {
		_spec.AddField(flight.FieldAvailableEconomySlot, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := fuo.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Flight{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
