// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessLevel is the predicate function for accesslevel builders.
type AccessLevel func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
